safe condition to avoid string index out of bounds
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

(cherry picked from commit 8f9ee45982a5a359405327b0812bb4819319274e)